[functions.bot]
enabled = true
verify_jwt = false
import_map = "./functions/bot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/bot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/bot/*.html" ]

[functions.envtest]
enabled = true
verify_jwt = false
import_map = "./functions/bot/deno.json"
entrypoint = "./functions/envtest.ts"
