project_id = "yad-crm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB" 